name: E2E Docker
on:
  workflow_run:
    workflows: ["Docker base image"]
    branches: [ master ]
    types: [ completed ]
  push:
    branches: [ master ]
    paths:
      - 'README2.md'
  workflow_dispatch:
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-20.04
    if: ${{ github.event.push != null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check if README.md has been changed as well
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | egrep 'README.md|')"

      - name: Debug variables
        run: |
          echo "Files: ${{ steps.getfile.outputs.files }}"
          echo "Workflow run: ${{ github.event.workflow_run }}"

      - name: Cancel workflow if README.md changed
        if: ${{ github.event.workflow_run == null && steps.getfile.outputs.files != '' }}
        uses: andymckay/cancel-action@0.2

      - name: Build me!
        run: |
          echo "Docker build"
          sleep 6
